# Generated by Django 5.2.8 on 2025-11-05 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(verbose_name='Озвученный текст')),
                ('audio_file_path', models.CharField(blank=True, max_length=255, verbose_name='Путь к аудиофайлу')),
                ('voice_id', models.CharField(default='EXAVITQu4vr4xnSDxYa4', max_length=50, verbose_name='ID голоса')),
                ('voice_settings', models.JSONField(blank=True, default=dict, null=True, verbose_name='Настройки голоса (стабильность, четкость и т.д.)')),
                ('model_id', models.CharField(default='eleven_multilingual_v2', max_length=100, verbose_name='ID модели синтеза')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на озвучивание',
                'verbose_name_plural': 'Запросы на озвучивание',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_voice_id', models.CharField(default='EXAVITQu4vr4xnSDxYa4', max_length=50, verbose_name='Голос по умолчанию')),
                ('default_voice_settings', models.JSONField(blank=True, default=dict, null=True, verbose_name='Настройки голоса по умолчанию')),
                ('default_model_id', models.CharField(default='eleven_multilingual_v2', max_length=100, verbose_name='Модель синтеза по умолчанию')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
