# Generated by Django 5.2.8 on 2025-11-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiospeaker_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speechrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
