# Generated by Django 5.2.8 on 2025-11-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiospeaker_app', '0002_remove_speechrequest_user_delete_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_audio_file', models.FileField(upload_to='uploads/', verbose_name='Загруженный аудиофайл')),
                ('recognized_text', models.TextField(blank=True, null=True, verbose_name='Распознанный текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('PENDING', 'В обработке'), ('COMPLETED', 'Завершено'), ('FAILED', 'Ошибка')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Запрос на распознавание',
                'verbose_name_plural': 'Запросы на распознавание',
                'ordering': ['-created_at'],
            },
        ),
    ]
