# Generated by Django 5.2.7 on 2025-11-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.FileField(upload_to='uploads/')),
                ('text_content', models.TextField()),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('ollama', 'Ollama'), ('tfidf', 'TF*IDF')], default='ollama', max_length=50)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='referate_creator_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('weight', models.FloatField(default=0.0)),
                ('order_in_text', models.IntegerField()),
                ('selected_for_summary', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='referate_creator_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('classic', 'Классический реферат'), ('keywords', 'Реферат ключевых слов')], max_length=20)),
                ('content', models.TextField()),
                ('generation_method', models.CharField(choices=[('tfidf', 'TF*IDF'), ('ollama', 'Ollama')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='referate_creator_app.document')),
            ],
        ),
    ]
