# Generated by Django 5.2.7 on 2025-11-18 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('text_content', models.TextField(verbose_name='Извлечённый текст')),
                ('detected_language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Определённый язык')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан ли документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='LanguageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('de', 'Немецкий')], max_length=2, unique=True, verbose_name='Язык')),
                ('word_frequencies', models.JSONField(default=dict, verbose_name='Частоты слов (метод частотных слов)')),
                ('short_word_frequencies', models.JSONField(default=dict, verbose_name='Частоты коротких слов')),
            ],
            options={
                'verbose_name': 'Языковой профиль',
                'verbose_name_plural': 'Языковые профили',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('freq', 'Метод частотных слов'), ('short', 'Метод коротких слов'), ('neural', 'Нейросетевой метод')], max_length=10, verbose_name='Метод')),
                ('detected_language', models.CharField(max_length=50, verbose_name='Определённый язык')),
                ('accuracy_score', models.FloatField(blank=True, null=True, verbose_name='Уверенность (точность)')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Время обработки (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата анализа')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='language_identifier_app.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Результат анализа',
                'verbose_name_plural': 'Результаты анализа',
                'ordering': ['-created_at'],
            },
        ),
    ]
