# Generated by Django 5.2.7 on 2025-11-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_identifier_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageprofile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], max_length=2, unique=True, verbose_name='Язык'),
        ),
    ]
